# Generated by Django 5.1.2 on 2024-10-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name="product's name")),
                ('price', models.PositiveBigIntegerField(verbose_name="product's price")),
                ('stock_quantity', models.PositiveIntegerField(verbose_name='quantity in stock')),
            ],
        ),
    ]
